#!/usr/bin/env bash
# =============================================================================
#  FactShield Edu — One-command startup
#  Works on a fresh clone. No Docker, no conda, no hardcoded paths.
#
#  Requirements:
#    - Python 3.10+ (3.11 recommended)
#    - Node.js 18+
#    - An OpenAI API key  (https://platform.openai.com/api-keys)
#
#  Usage:
#    chmod +x run_app.sh
#    ./run_app.sh
# =============================================================================

set -e

# ── Resolve paths ─────────────────────────────────────────────────────────────
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$DIR/backend"
FRONTEND_DIR="$DIR/frontend"
VENV_DIR="$DIR/.venv"
ENV_FILE="$BACKEND_DIR/.env"

# ── Terminal colours ──────────────────────────────────────────────────────────
BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
CYAN="\033[0;36m"
RESET="\033[0m"

info()  { echo -e "  ${GREEN}✓${RESET}  $1"; }
warn()  { echo -e "  ${YELLOW}!${RESET}  $1"; }
error() { echo -e "\n  ${RED}✗  ERROR: $1${RESET}\n"; exit 1; }
step()  { echo -e "\n${CYAN}${BOLD}▶  $1${RESET}"; }

echo -e "\n${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}   FactShield Edu — AI Education Assistant${RESET}"
echo -e "${BOLD}   3-Pipeline Hallucination Detection System${RESET}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"


# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — Prerequisites
# ─────────────────────────────────────────────────────────────────────────────
step "Checking prerequisites"

# Python 3.10+
PYTHON=""
for cmd in python3.11 python3.12 python3.10 python3 python; do
    if command -v "$cmd" &>/dev/null; then
        if "$cmd" -c "import sys; exit(0 if sys.version_info >= (3, 10) else 1)" 2>/dev/null; then
            PYTHON="$cmd"
            break
        fi
    fi
done
[ -z "$PYTHON" ] && error "Python 3.10 or newer is required.\n     Install from: https://www.python.org/downloads/"
info "Python: $($PYTHON --version)"

# Node.js 18+
command -v node &>/dev/null || error "Node.js 18+ is required.\n     Install from: https://nodejs.org"
NODE_MAJOR=$(node -e "console.log(parseInt(process.version.slice(1)))")
[ "$NODE_MAJOR" -lt 16 ] && error "Node.js 16+ required (found $(node --version))."
info "Node.js: $(node --version)"

# npm
command -v npm &>/dev/null || error "npm is required (comes with Node.js)."
info "npm: $(npm --version)"

# curl (for health check)
command -v curl &>/dev/null || warn "curl not found — skipping backend health check."


# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — Python virtual environment
# ─────────────────────────────────────────────────────────────────────────────
step "Python virtual environment"

if [ ! -d "$VENV_DIR" ]; then
    echo "  Creating .venv ..."
    "$PYTHON" -m venv "$VENV_DIR"
    info "Virtual environment created at .venv"
else
    info "Virtual environment already exists (.venv)"
fi

PY="$VENV_DIR/bin/python"
PIP="$VENV_DIR/bin/pip"


# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Backend Python dependencies
# ─────────────────────────────────────────────────────────────────────────────
step "Installing backend dependencies"
warn "Includes PyTorch, Transformers, BERTScore — first install takes 5–15 min."

"$PIP" install --upgrade pip --quiet
"$PIP" install -r "$BACKEND_DIR/requirements.txt"
info "All backend packages installed."


# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — Environment file (.env)
# ─────────────────────────────────────────────────────────────────────────────
step "Environment configuration"

if [ ! -f "$ENV_FILE" ]; then
    echo ""
    warn "No backend/.env found — creating one now."
    echo ""

    # Prompt for OpenAI key
    echo -e "  ${BOLD}OpenAI API key${RESET} (required for GPT-4o-mini + real token logprobs)"
    echo -e "  Get one at: https://platform.openai.com/api-keys"
    echo -n "  Enter your key (sk-...): "
    read -r OPENAI_KEY
    echo ""

    echo -e "  ${BOLD}Gemini API key${RESET} (optional — used as LLM fallback)"
    echo -e "  Get one at: https://aistudio.google.com/app/apikey"
    echo -n "  Enter your key (or press Enter to skip): "
    read -r GEMINI_KEY
    echo ""

    cat > "$ENV_FILE" << EOF
# FactShield Environment Configuration
# Generated by run_app.sh — edit this file to update keys.

# Primary LLM — GPT-4o-mini (real logprobs needed for Pipeline 3)
OPENAI_API_KEY=${OPENAI_KEY}

# Fallback LLM — Gemini 2.5 Flash (optional)
GEMINI_API_KEY=${GEMINI_KEY}

# Database — SQLite (no Docker or Postgres needed)
DATABASE_URL=sqlite+aiosqlite:///./factshield.db

# Vector store path
CHROMA_PERSIST_DIR=./chroma_db
EOF
    info ".env file created at backend/.env"
else
    info "Found existing backend/.env"

    # Warn if key is still empty
    if grep -q "^OPENAI_API_KEY=$" "$ENV_FILE" 2>/dev/null; then
        warn "OPENAI_API_KEY is empty in backend/.env"
        warn "Add your key to use GPT-4o-mini. The app will fall back to Gemini/Ollama."
    fi
fi


# ─────────────────────────────────────────────────────────────────────────────
# STEP 5 — Database setup
# ─────────────────────────────────────────────────────────────────────────────
step "Database setup"

cd "$BACKEND_DIR"

# Ensure the .env DATABASE_URL is SQLite (patch if it still has the old Postgres default)
if grep -q "postgresql" "$ENV_FILE" 2>/dev/null; then
    warn "DATABASE_URL in .env points to PostgreSQL."
    warn "Switching to SQLite for zero-config local setup..."
    # Replace the DATABASE_URL line
    sed -i.bak 's|^DATABASE_URL=.*|DATABASE_URL=sqlite+aiosqlite:///./factshield.db|' "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
    info "DATABASE_URL updated to SQLite."
fi

# Run Alembic migrations (creates tables on first run, upgrades on subsequent runs)
echo "  Running Alembic migrations..."
PYTHONPATH="$DIR" "$VENV_DIR/bin/alembic" upgrade head 2>&1 | sed 's/^/    /'
info "Database schema ready."


# ─────────────────────────────────────────────────────────────────────────────
# STEP 6 — Frontend dependencies
# ─────────────────────────────────────────────────────────────────────────────
step "Installing frontend dependencies"

cd "$FRONTEND_DIR"
npm install --silent
info "Frontend packages installed."


# ─────────────────────────────────────────────────────────────────────────────
# STEP 7 — Start servers
# ─────────────────────────────────────────────────────────────────────────────
step "Starting FactShield"

# Backend
cd "$BACKEND_DIR"
PYTHONPATH="$DIR" \
nohup "$VENV_DIR/bin/uvicorn" app.main:app \
    --host 0.0.0.0 \
    --port 8000 \
    --log-level warning \
    > backend.log 2>&1 &
BACKEND_PID=$!

# Frontend
cd "$FRONTEND_DIR"
nohup npm run dev > frontend.log 2>&1 &
FRONTEND_PID=$!

# Wait for backend to come up (max 20s)
echo "  Waiting for backend..."
READY=0
for i in {1..20}; do
    if curl -s -o /dev/null http://localhost:8000/api/v1/student/concept-guide 2>/dev/null; then
        READY=1
        break
    fi
    sleep 1
    echo -n "."
done
[ "$READY" -eq 1 ] && echo "" || echo -e "\n  ${YELLOW}Backend may still be initialising — check backend/backend.log${RESET}"

# Wait for frontend (max 10s)
echo "  Waiting for frontend..."
for i in {1..10}; do
    if curl -s -o /dev/null http://localhost:5173 2>/dev/null; then
        break
    fi
    sleep 1
    echo -n "."
done
echo ""

info "Backend  → http://localhost:8000  (logs: backend/backend.log)"
info "Frontend → http://localhost:5173  (logs: frontend/frontend.log)"

# Save PIDs so the user can stop them easily
echo "$BACKEND_PID $FRONTEND_PID" > "$DIR/.factshield_pids"


# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}${BOLD}   FactShield is running!${RESET}"
echo -e ""
echo -e "   ${BOLD}Open in browser:${RESET}  http://localhost:5173"
echo -e "   ${BOLD}API docs:${RESET}         http://localhost:8000/docs"
echo -e ""
echo -e "   To stop:   ${CYAN}kill \$(cat .factshield_pids)${RESET}"
echo -e "   API key:   ${CYAN}backend/.env${RESET}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n"

# Note about first ML model load
echo -e "  ${YELLOW}Note:${RESET} The first query will download ML models (MiniCheck, BERTScore)."
echo -e "        This takes 1–2 min on the first run. Subsequent starts are instant.\n"
