"""Add mode to semantic_cache

Revision ID: 322cf791b35b
Revises: f3e4b5c6d7e8
Create Date: 2026-07-05 17:15:40.280815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322cf791b35b'
down_revision: Union[str, Sequence[str], None] = 'f3e4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semantic_cache', sa.Column('mode', sa.String(), server_default='unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semantic_cache', 'mode')
    # ### end Alembic commands ###
